#!/bin/sh -
#
# SPDX-FileCopyrightText: Copyright 2024 OK Ryoko
# SPDX-License-Identifier: MIT

set -eu

# filter prints the lines in a sequence that match a pattern, assuming the
# availability of grep(1).
#
# Parameters:
#
#   $1: string, a regular expression
#   $2: string, a newline-delimited sequence of text items to filter
#
filter() {
	printf '%s\n' "$(
		echo "$1" | { grep -e "$2" || test $? = 1; }
	)"
}

# Handle the case where there are no commits in the local repository
#
if git rev-parse --verify HEAD > '/dev/null' 2>&1; then
	against=HEAD
else
	against="$(git hash-object -t tree '/dev/null')"
fi
readonly against

# Capture the names of all files in the index, exiting early if there are no
# changes
#
files="$(git diff --staged --name-only --diff-filter=ACMR "${against}")"
if [ -z "${files}" ]; then
	exit 0
fi
readonly files

# Check all changed Markdown files
#
readonly md_pattern='^.*\.md$'
md_files="$(filter "${md_pattern}" "${files}")"
readonly md_files
if [ -n "${md_files}" ]; then
	# shellcheck disable=SC2086
	mdl ${md_files}
fi

exit 0
